stages:
  - triggers

trigger_cms:
  stage: triggers
  trigger:
    include: src/.gitlab-ci.yml
  rules:
    - if: ($CI_COMMIT_BRANCH == "main")
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' #disable detached pipeline run upon open of merge request
      when: never
    