variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
stages: 
  - build 
  - test 
  - sonar
  - deploy 
 
build_project: 
  stage: build 
  script: 
    - echo "this is sample project, $GITLAB_USER_LOGIN!"
    
testing1: 
  stage: test 
  script: 
    - echo "This job test for user login sucessfully" 
 
testing2: 
  stage: test 
  script: 
    - echo "This job tests userlog, but takes more time than test-job1." 
    - echo "After the echo commands complete, it runs the sleep command for 5 seconds" 
    - sleep 5 
 
sonarcloud-check:
  stage : sonar
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
 
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner 
  only:
    - merge_requests
    - master
    - develop
 
deploy-prod: 
  stage: deploy 
  script: 
    - echo "This job deploys for some usr files  $CI_COMMIT_BRANCH branch." 